// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package testpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// User - chat user info
type User struct {
	// nickName - User's nickname
	NickName string `protobuf:"bytes,1,opt,name=nickName,proto3" json:"nickName,omitempty"`
	// userID - User's unique identifier
	UserID string `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	// userName - Username
	UserName             string   `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_de5e90285f49cfd9, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *User) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

// Message - message
type Message struct {
	// chatID - The globally unique identifier of the message, in a format similar to userid:msgid
	ChatID string `protobuf:"bytes,1,opt,name=chatID,proto3" json:"chatID,omitempty"`
	// from - Message user
	From *User `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// to - User receiving the message
	To *User `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	// text - Message text content
	Text string `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	// timeStamp - Time of sending a message
	TimeStamp            int64    `protobuf:"varint,5,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_de5e90285f49cfd9, []int{1}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetChatID() string {
	if m != nil {
		return m.ChatID
	}
	return ""
}

func (m *Message) GetFrom() *User {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Message) GetTo() *User {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Message) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

// UserList - user list
type UserList struct {
	// users - user list
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserList) Reset()         { *m = UserList{} }
func (m *UserList) String() string { return proto.CompactTextString(m) }
func (*UserList) ProtoMessage()    {}
func (*UserList) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_de5e90285f49cfd9, []int{2}
}
func (m *UserList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserList.Unmarshal(m, b)
}
func (m *UserList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserList.Marshal(b, m, deterministic)
}
func (dst *UserList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserList.Merge(dst, src)
}
func (m *UserList) XXX_Size() int {
	return xxx_messageInfo_UserList.Size(m)
}
func (m *UserList) XXX_DiscardUnknown() {
	xxx_messageInfo_UserList.DiscardUnknown(m)
}

var xxx_messageInfo_UserList proto.InternalMessageInfo

func (m *UserList) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "testpb.User")
	proto.RegisterType((*Message)(nil), "testpb.Message")
	proto.RegisterType((*UserList)(nil), "testpb.UserList")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_test_de5e90285f49cfd9) }

var fileDescriptor_test_de5e90285f49cfd9 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xb1, 0x4a, 0xc5, 0x30,
	0x14, 0x86, 0x49, 0x9b, 0x5b, 0xef, 0x3d, 0x3a, 0x9d, 0x41, 0x82, 0xdc, 0x21, 0x64, 0xea, 0x94,
	0x41, 0x5f, 0xa1, 0x4b, 0x41, 0x1d, 0x2a, 0xba, 0xa7, 0x25, 0x6a, 0x91, 0x98, 0x92, 0x1c, 0xc1,
	0xf7, 0xf0, 0x85, 0x25, 0xa7, 0x55, 0xc1, 0xbb, 0x9d, 0x3f, 0x3f, 0xdf, 0xc7, 0x4f, 0x00, 0xc8,
	0x67, 0xb2, 0x4b, 0x8a, 0x14, 0xb1, 0x29, 0xf7, 0x32, 0x9a, 0x27, 0x90, 0x8f, 0xd9, 0x27, 0xbc,
	0x82, 0xfd, 0xfb, 0x3c, 0xbd, 0xdd, 0xbb, 0xe0, 0x95, 0xd0, 0xa2, 0x3d, 0x0c, 0xbf, 0x19, 0x2f,
	0xa1, 0xf9, 0xc8, 0x3e, 0xf5, 0x9d, 0xaa, 0xb8, 0xd9, 0x52, 0x61, 0xca, 0xc5, 0x4c, 0xbd, 0x32,
	0x3f, 0xd9, 0x7c, 0x09, 0x38, 0xbb, 0xf3, 0x39, 0xbb, 0x17, 0xe6, 0xa7, 0x57, 0x47, 0x7d, 0xb7,
	0x99, 0xb7, 0x84, 0x1a, 0xe4, 0x73, 0x8a, 0x81, 0xad, 0xe7, 0xd7, 0x17, 0x76, 0x9d, 0x64, 0xcb,
	0x9e, 0x81, 0x1b, 0x3c, 0x42, 0x45, 0x91, 0xdd, 0xff, 0xfb, 0x8a, 0x22, 0x22, 0x48, 0xf2, 0x9f,
	0xa4, 0x24, 0x5b, 0xf9, 0xc6, 0x23, 0x1c, 0x68, 0x0e, 0xfe, 0x81, 0x5c, 0x58, 0xd4, 0x4e, 0x8b,
	0xb6, 0x1e, 0xfe, 0x1e, 0x8c, 0x85, 0x7d, 0xa1, 0x6f, 0xe7, 0x4c, 0x68, 0x60, 0x57, 0xd6, 0x66,
	0x25, 0x74, 0x7d, 0xa2, 0x5f, 0xab, 0xb1, 0xe1, 0xcf, 0xba, 0xf9, 0x0e, 0x00, 0x00, 0xff, 0xff,
	0xb4, 0xa3, 0x13, 0x04, 0x3a, 0x01, 0x00, 0x00,
}
