FROM golang:1.12

MAINTAINER zerro "zerrozhao@gmail.com"

ENV GOPROXY https://goproxy.io

WORKDIR /app/ankadb

COPY ./go.* /app/ankadb/

RUN go mod download

COPY . /app/ankadb

RUN go test ./... -cover